name : Anagh Sharma
brand : Portfolio
description : This is my personal website
keyword : 
url : http://www.anaghsharma.com
email : mailto:anaghsharma12@gmail.com
twitter : https://twitter.com/AnaghSharma
github : https://github.com/AnaghSharma
dribbble : https://dribbble.com/AnaghSharma
behance : https://www.behance.net/AnaghSharma
facebook : https://www.facebook.com/anaghsharma12
linkedin: https://www.linkedin.com/in/anaghsharma/
author : Anagh Sharma
year : 2018
markdown : kramdown
include : ['_pages']
exclude :
  - node_modules
