name : Anagh Sharma
brand : Portfolio
description : This is my personal website
keyword : 
url : https://anaghsharma.github.io
email : anaghsharma12@gmail.com
twitter : AnaghSharma
github : AnaghSharma
dribbble : AnaghSharma
behance : AnaghSharma
author : Anagh Sharma
year : 2017
markdown : kramdown
exclude :
  - node_modules
