name : Foundation5/github pages/Jykill starter
brand : My Project
description : This is the description of my project
keyword : 
url : http://daigofuji.github.io/jekyll-foundation-6-starter/
email : daigo@daigofujiwara.com
twitter : DaigoFuji
github : DaigoFuji
author : Daigo Fujiwara
year : 2016
markdown : kramdown
exclude :
  - node_modules
